//CAN BUS related stuff
#define CAN_SPEED 100E3

//LoRa related stuff
#define CFG_eu868 1
#define LORAWAN_TX_INTERVAL 60 // in seconds

//timeouts
#define HEADSTATION_TIMEOUT 3*10000 // in milliseconds
#define HEADSTATION_ID 0 

//packet identifiers
#define ENTRY_PACKET 1
#define LEAVE_PACKET 2
#define ALIVE_PACKET 3

#define SENSOR_REGISTER_PACKET 80
#define SENSOR_REGISTER_ACK_PACKET 81
#define SENSOR_UNREGISTER_PACKET 82
#define SENSOR_UNREGISTER_ACK_PACKET 83

#define CALIBRATION_REQUEST 40
#define CALIBRATION_RESPONSE 41
#define CALIBRATION_ACK 42

#define CALIBRATION_ERR_INVALID_SLOT 62


#define VALUE_REQUEST 70
#define VALUE_REQUEST_ACK 71
#define VALUE_RESPONSE 72